### PR TITLE
COMP: Include version tags in python setup.py

### PR DESCRIPTION
**Pull request by richardbeare**
Minimum ITK version at 5.1.0
Bump version of this module to 1.0.1

### CODE REVIEW

**Comment by richardbeare** [comment]
@thewtex are the macosx failures expected?

**Comment by thewtex** [comment]
@richardbeare this repository is behind *InsightSoftwareConsortium/ITKParabolicMorphology* -- all builds should be green.

**Comment by richardbeare** [comment]
Pretty sure it isn't behind (assuming I should use ITKparabolicmorphology/master). Last commit is from you. This time I've sent the PR to the upstream instead of myself....

**Comment by thewtex** [comment]
It looks like, at some point the repository was forked to the *InsightSoftwareConsortium* organization. This is nice because it recognizes your original authorship. An other option would have been to use the GitHub repository transfer tools. In either case, you should have administrative access to the repository and should be credited appropriately. If this is not the case, please let @jhlegarreta, @hjmjohnson or myself know.

**Pull request merged**
